### PR TITLE
catch exception

### PR DESCRIPTION
**Pull request by edditler**

### CODE REVIEW

**Comment by oschuett** [comment]
The travis build fails because one of the lines is too long.

To reproduce this locally run docker build with `--no-cache` and make sure you have the latest `ubuntu:rolling` image. How about moving the try/catch up to [line 47](https://github.com/cp2k/aiida-cp2k/blob/master/aiida_cp2k/parsers/__init__.py#L47) ? This way we would be protected against all kinds of failure modes.

**Comment by edditler** [comment]
Using a blank `except: ` block would make this even more robust, but the linter would complain so I leave `except KeyError:`.

**Comment by oschuett** [comment]
What do you think about this: https://github.com/cp2k/aiida-cp2k/pull/11 .

**Comment by edditler** [comment]
I didn't know about this. Seems good to me.

**Comment by oschuett** [comment]
Ok, I committed it. Take it for a spin. I'll push a new release to pypi later this week.

**Pull request closed without merging**
